### ISSUE TITLE
Usage Case Equality

### ISSUE THREAD

**Issue by gpltaylor** [DzoQiEuoi/pure-bind#1]
I'm reviewing the functionality of this within my existing application. I believe the main goal of this library is memoization. To test this I have created the following sample.

I am expecting that x1A and x2A to have the same object (pointer reference). However, this is comparing as false. Am I miss understanding the nature of this library?

```
var bind = require("pure-bind")

var doSomething = (a,b) => {
    return { 
        a, b, answer: a * b
    }
}

var x1 = bind.default(doSomething,2,3)
var x2 = bind.default(doSomething,2,3)

x1A = x1()
x2A = x2()

x1A == x2A // Expected True, but get False
````

**Comment by sushant24** [comment]
This is the correct behavior since it caches only the function not the result. 
```
var pureBind = require("pure-bind")
var doSomething = (a,b) => {
    return { 
        a, b, answer: a * b
    }
}

var x1 = pureBind.default(doSomething,2,3)
var x2 = pureBind.default(doSomething,2,3)

x1A = x1()
x2A = x2()
x1B = x1()

console.log(x1 === x2);//True since they are the same function

//Return false as the function returns new instance on every invocation
console.log(x1A == x2A) //Return false
console.log(x1A == x1B)//Return false
```

**Comment by DzoQiEuoi** [comment]
sushant24 is correct.

The purpose of the library is to maintain reference equality of the functions rather than their return values. This can be useful when you want to bind a value to a function as your pass it into a React component because it prevents unnecessary virtual DOM re-renders.
